/**
 * Style Dictionary v4 config — generates tokens.css
 * Run: node style-dictionary/config.mjs
 * Dart files are generated separately by scripts/generate-dart.mjs
 */

import StyleDictionary from 'style-dictionary';
import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, '..');

mkdirSync(join(root, 'build/css'), { recursive: true });

// ─── Transforms ──────────────────────────────────────────────────────────────

// dimension → Npx (skip 9999 which is a placeholder for "none")
StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  filter: (token) => {
    const type = token.$type ?? token.type;
    const value = token.$value ?? token.value;
    return type === 'dimension' && typeof value === 'number' && value !== 9999;
  },
  transform: (token) => `${token.$value ?? token.value}px`,
});

// 9999 placeholder → CSS none (used for mobile max-width/max-text-width)
StyleDictionary.registerTransform({
  name: 'dimension/none',
  type: 'value',
  filter: (token) => (token.$value ?? token.value) === 9999,
  transform: () => 'none',
});

// ─── Custom CSS format (single selector block) ───────────────────────────────

StyleDictionary.registerFormat({
  name: 'css/selector',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const lines = dictionary.allTokens.map((token) => {
      const originalValue = token.original?.$value ?? token.original?.value;
      let value = token.$value ?? token.value;

      // If the original was a reference, output a CSS var() instead of the resolved hex.
      // This keeps the cascade readable in DevTools.
      if (typeof originalValue === 'string' && originalValue.startsWith('{')) {
        const refPath = originalValue.slice(1, -1); // strip { }
        value = `var(--${refPath.replace(/\./g, '-')})`;
      }

      return `  --${token.name}: ${value};`;
    });

    const header = `/* ${selector} */`;
    return `${header}\n${selector} {\n${lines.join('\n')}\n}\n`;
  },
});

// ─── Helper: build one SD instance ───────────────────────────────────────────

async function build({ sources, filterFile, selector, outFile }) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: sources.map((s) => join(root, s)),
    platforms: {
      css: {
        // Explicit transforms — no transformGroup so the built-in size/rem doesn't conflict
        transforms: ['name/kebab', 'color/css', 'size/px', 'dimension/none'],
        prefix: '',
        files: [
          {
            destination: join(root, outFile),
            format: 'css/selector',
            filter: filterFile ? (token) => token.filePath.includes(filterFile) : undefined,
            options: { selector },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

// ─── 1. Primitives → :root ───────────────────────────────────────────────────
await build({
  sources: ['tokens/primitives.json'],
  filterFile: 'primitives',
  selector: ':root',
  outFile: 'build/css/_primitives.css',
});

// ─── 2. Semantic light + web dimensions → :root ──────────────────────────────
await build({
  sources: ['tokens/primitives.json', 'tokens/color.light.json', 'tokens/dimensions.web.json'],
  filterFile: null,
  selector: ':root',
  outFile: 'build/css/_semantic-web-light.css',
});

// ─── 3. Semantic dark → [data-theme="dark"] ──────────────────────────────────
await build({
  sources: ['tokens/primitives.json', 'tokens/color.dark.json'],
  filterFile: 'color.dark',
  selector: '[data-theme="dark"]',
  outFile: 'build/css/_dark.css',
});

// ─── 4. Mobile dimensions → [data-platform="mobile"] ────────────────────────
await build({
  sources: ['tokens/primitives.json', 'tokens/dimensions.mobile.json'],
  filterFile: 'dimensions.mobile',
  selector: '[data-platform="mobile"]',
  outFile: 'build/css/_mobile.css',
});

// ─── Concatenate into tokens.css ─────────────────────────────────────────────
import { readFileSync } from 'fs';

const parts = [
  '/* Generated by Style Dictionary — do not edit by hand */',
  '/* Run: npm run build:tokens                            */',
  '',
  readFileSync(join(root, 'build/css/_primitives.css'), 'utf8'),
  readFileSync(join(root, 'build/css/_semantic-web-light.css'), 'utf8'),
  readFileSync(join(root, 'build/css/_dark.css'), 'utf8'),
  readFileSync(join(root, 'build/css/_mobile.css'), 'utf8'),
];

writeFileSync(join(root, 'build/css/tokens.css'), parts.join('\n'));

console.log('✅  build/css/tokens.css written');
